### ISSUE TITLE
roadmap for brainhack

### ISSUE THREAD

**Issue by PeerHerholz** [PeerHerholz/BIDSonym#1]
- [ ]  algorithms 
  - [x] [pydeface](https://github.com/poldracklab/pydeface)
  - [x] [mri_deface](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_deface)
  - [ ] [de-identification toolbox](https://www.nitrc.org/projects/de-identification/)
  - [x] [Quickshear](https://github.com/nipy/quickshear)

- [x] docker image
   - [x] necessary software
         -  [FSL](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)
         - [FreeSurfer](https://surfer.nmr.mgh.harvard.edu)
         -  [NiBabel](http://nipy.org/nibabel/)
         -  [Nipype](https://nipype.readthedocs.io/en/latest/)
   - [x] [neurodocker](https://github.com/kaczmarj/neurodocker)
   - [ ] [reprozip](https://github.com/kaczmarj/neurodocker#minimize-existing-docker-image)
- [x] readme file
  - [x]  Project description
  - [x]  Documentation
  - [x]  How to report errors
  - [x]  Acknowledgments
  - [x]  Usage
- [ ]
- [ ]
- [ ]

**Comment by PeerHerholz** [comment]
Closing this, given that most things are implement and the current status of the project.
